"""empty message

Revision ID: 1432cee2de58
Revises: 44cea4df3a41
Create Date: 2016-07-06 09:12:30.850762

"""

# revision identifiers, used by Alembic.
revision = '1432cee2de58'
down_revision = '44cea4df3a41'

from alembic import op, context
import sqlalchemy as sa
from flask import current_app


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colour', sa.String(), nullable=True),
    sa.Column('shape', sa.String(), nullable=True),
    sa.Column('exploded', sa.Boolean(), nullable=True),
    sa.Column('gadget_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gadget_id'], ['gadget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'gadget', sa.Column('power', sa.Boolean(), nullable=True))

    # MANUALLY ADDED the line below to grant permissions for the user found in config variable APP_SQL_USERNAME on table widget.
    context.execute("GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE widget TO " + current_app.config.get('APP_SQL_USERNAME'))
    context.execute("GRANT USAGE, SELECT ON SEQUENCE widget_id_seq TO " + current_app.config.get('APP_SQL_USERNAME'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'gadget', 'power')
    op.drop_table('widget')
    ### end Alembic commands ###
