"""empty message

Revision ID: 44cea4df3a41
Revises: None
Create Date: 2016-07-05 10:54:23.205005

"""

# revision identifiers, used by Alembic.
revision = '44cea4df3a41'
down_revision = None

from alembic import op, context
import sqlalchemy as sa
from flask import current_app


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gadget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # MANUALLY ADDED the line below to grant permissions for the user found in config variable APP_SQL_USERNAME on table gadget.
    context.execute("GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE gadget TO " + current_app.config.get('APP_SQL_USERNAME'))
    context.execute("GRANT USAGE, SELECT ON SEQUENCE gadget_id_seq TO " + current_app.config.get('APP_SQL_USERNAME'))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gadget')
    ### end Alembic commands ###
